# Dockerfile para rodar um app de Streamlit
FROM python:3.9

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copie os arquivos necessários para o diretório de trabalho
COPY requirements.txt ./
COPY . .

# Instale as dependências]
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Exponha a porta em que o Streamlit rodará
EXPOSE 8502

# Comando para iniciar o Streamlit
CMD ["streamlit", "run", "airConditioningConsumption.py", "--server.port=8501"]
